version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: wednesday
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    groups:
      production-patch-minor:
        applies-to: version-updates
        dependency-type: production
        update-types:
          - minor
          - patch
      development-patch-minor:
        applies-to: version-updates
        dependency-type: development
        update-types:
          - minor
          - patch
