import type { PetCharacterId } from "./PetGame";
import { DECORATION_ASSETS } from "./decorationAssets";

export const GAME_ASSETS = {
  room: "/manus-storage/nivel-01-lar_5a7be3d2.webp",
  kitten: "/manus-storage/meu-pet-gatinho_11ce8df9.png",
  levels: [
    "/manus-storage/nivel-01-lar_5a7be3d2.webp",
    "/manus-storage/nivel-02-jardim_c6748045.webp",
    "/manus-storage/nivel-03-feira_e7681b3d.webp",
    "/manus-storage/nivel-04-telhado_eb67ef05.webp",
    "/manus-storage/nivel-05-praia_cd543731.webp",
    "/manus-storage/nivel-06-bosque_f6f3b9ac.webp",
    "/manus-storage/nivel-07-neve_76e65b80.webp",
    "/manus-storage/nivel-08-biblioteca_1f35f2af.webp",
    "/manus-storage/nivel-09-observatorio_0ab887b5.webp",
    "/manus-storage/nivel-10-festival_66c3d976.webp",
  ],
  accessories: {
    boy: "/manus-storage/acessorio-bone_b2ac489b.webp",
    girl: "/manus-storage/acessorio-laco_0330607b.webp",
  },
  characters: {
    "menino-prata": "/manus-storage/boy-prata_33684c26.webp",
    "menino-laranja": "/manus-storage/boy-laranja_d9796f62.webp",
    "menino-preto": "/manus-storage/boy-preto_954326d9.webp",
    "menina-creme": "/manus-storage/girl-creme_d39b0cb1.webp",
    "menina-calico": "/manus-storage/girl-calico_fece88f9.webp",
    "menina-azul": "/manus-storage/girl-azul_75498a70.webp",
  } satisfies Record<PetCharacterId, string>,
  companions: {
    mimi: "/manus-storage/companheira-mimi_bc963ec5.webp",
    tico: "/manus-storage/companheiro-tico_da6d680c.webp",
    mimo: "/manus-storage/mascot-01-mimo_31fcb547.webp",
    florita: "/manus-storage/mascot-02-florita_7e059aa6.webp",
    bigodito: "/manus-storage/mascot-03-bigodito_f3a981ff.webp",
    sol: "/manus-storage/mascot-04-sol_d636860d.webp",
    conchinha: "/manus-storage/mascot-05-conchinha_9e16f10c.webp",
    pingo: "/manus-storage/mascot-06-pingo_c29b94c2.webp",
    nevinha: "/manus-storage/mascot-07-nevinha_fbd8e97e.webp",
    letrinha: "/manus-storage/mascot-08-letrinha_289c9a17.webp",
    estrelinha: "/manus-storage/mascot-09-estrelinha_71ec038f.webp",
    festeiro: "/manus-storage/mascot-10-festeiro_0c19a065.webp",
  },
  creatorPlaque: "/manus-storage/allana-gabriela-portrait_0da1a95d.webp",
  decorations: DECORATION_ASSETS,
  gift: "/manus-storage/gift-surprise_b76a0e8d.webp",
  platformer: {
    grass: "/manus-storage/platform-grass_c043c1f0.webp",
    terrain: "/manus-storage/grass-earth-side-tile_30281d00.webp",
    portal: "/manus-storage/goal-portal_e4d6bfa1.webp",
    cats: {
      "menino-prata": "/manus-storage/menino-prata-run_7ef210ee.webp",
      "menino-laranja": "/manus-storage/menino-laranja-run_7312d456.webp",
      "menino-preto": "/manus-storage/menino-preto-run_1fb44eca.webp",
      "menina-creme": "/manus-storage/menina-creme-run_91a56382.webp",
      "menina-calico": "/manus-storage/menina-calico-run_f1dd7f6b.webp",
      "menina-azul": "/manus-storage/menina-azul-run_1e430122.webp",
    } satisfies Record<PetCharacterId, string>,
  },
  icon: "/manus-storage/app-icon_5164c636.webp",
  voice: {
    intro: "/manus-storage/onboarding-intro_8ecc6b01.mp3",
    welcome: "/manus-storage/voz-boas-vindas_487ef5ce.mp3",
    welcomeBoy: "/manus-storage/welcome-boy_d22a0e56.mp3",
    welcomeGirl: "/manus-storage/welcome-girl_6f356a4f.mp3",
    care: "/manus-storage/voz-cuidado_0e8c8bfd.mp3",
    careBoy: "/manus-storage/pet-care-boy_8e18ef48.mp3",
    careGirl: "/manus-storage/pet-care-girl_35dd9364.mp3",
    tapBoy: "/manus-storage/pet-tap-boy_148f8d0b.mp3",
    tapGirl: "/manus-storage/pet-tap-girl_7ebb90e7.mp3",
    level: "/manus-storage/voz-nivel_c6656468.mp3",
    levelBoy: "/manus-storage/level-boy_832a2a02.mp3",
    levelGirl: "/manus-storage/level-girl_4aa80753.mp3",
    mimi: "/manus-storage/voice-mimi_55dee263.mp3",
    tico: "/manus-storage/voice-tico_8f84daf9.mp3",
  },
  sounds: {
    match: "/manus-storage/match-combo_c86aadd7.mp3",
  },
} as const;
